### ISSUE TITLE
testing checklist

### ISSUE THREAD

**Issue by saucepoint** [z0r0z/v4-router#18]
(fuzzing zeroForOne)
- [x] test_single_exactInput
- [x] test_single_exactInput_native
- [x] test_single_exactInput_hookData
- [x] test_single_exactInput_customCurve

---

- [x] test_single_exactOutput
- [x] test_single_exactOutput_native
- [x] test_single_exactOutput_hookData
- [x] test_single_exactInput_customCurve

---

- [x] test_multi_exactInput
- [x] test_multi_exactInput_native
- [x] test_multi_exactInput_hookData
- [x] test_multi_exactInput_customCurve

---

- [x] test_multi_exactOutput
- [x] test_multi_exactOutput_native
- [x] test_multi_exactOutput_hookData
- [x] test_multi_exactOutput_customCurve
